nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: DAC21636-1930-4126-B0A9-0EFBFBF0A2E8
    npmRegistryServer: "https://npm.fontawesome.com/"
